services:
  - type: web
    name: fruit-ai
    env: python
    plan: starter
    pythonVersion: 3.10.13
    buildCommand: pip install --upgrade pip && pip install -r requirments.txt
    startCommand: gunicorn app:app
